# Railway Deployment Configuration
# This file tells Railway how to deploy your backend API

[build]
  command = "npm install"

[deploy]
  command = "node minimal-setup.js && npm start"

[env]
  NODE_ENV = "production"
